name: Interest Contract

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

env: 
    RUST_BACKTRACE: 1

jobs:
  ci:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: 
          - build: macOS
            os: macOS-latest
          - build: ubuntu
            os: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./contracts/interest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
          components: clippy,rustfmt
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Formatting
        run: cargo fmt -- --check
      - name: Build
        run: RUSTFLAGS='-C link-arg=-s' cargo wasm --locked
      - name: Unit Test
        run: cargo unit-test --locked